# -*- coding: utf-8 -*-
"""Ejercicio Caracteres - RNP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fzaBs2kFnuzDpmT11G1G_r34-w4kAope

# Aprendizaje Supervisado - Redes Neuronales

1. Preparación de Datos
2. División de los datos
3. Aprendizaje del Modelo
4. Evaluación del Modelo
5. Predicción de Datos Futuros
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# 1. Preparación de Datos
-  Cargamos los datos
-  Conocemos los datos con estadísticos
- Transformación de datos  (sklearn sólo analiza variables numéricas)
"""

#Cargamos los datos
data = pd.read_excel("alfabeto.xlsx", sheet_name="alfabeto")
data.head()

#Conocemos los datos
data.info()

#Corrección del tipo de datos
data['letra']=data['letra'].astype('category') #Se corrige el tipo de dato object a category dataframe['Columna']
data.info()

#Descripción de variables numéricas
print(data.describe());
data.plot.hist(bins=5);

from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
data["letra"] = enc.fit_transform(data["letra"])
data["letra"]

#Descripción variables categóricas
data['letra'].value_counts().plot(kind='bar')

"""# 2. División 70-30"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data.drop("letra", axis = 1) 
Y = data['letra']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y)
Y_train.value_counts()

"""# 3. Aprendizaje del Modelo: Red Neuronal"""

#Creación del modelo con el conjunto de entrenamiento
from keras.models import Sequential
from keras.layers.core import Dense
#Red neuronal
model = Sequential()
model.add(Dense(50, input_dim = 35, activation = 'relu'))
model.add(Dense(15, activation = 'relu'))
model.add(Dense(1, activation = 'relu')) # Capa de salida
model.compile(loss = 'mean_squared_error', optimizer = 'adam', metrics = ['accuracy'])
model.fit(X_train, Y_train, epochs=180)

"""# 4. Evaluación del modelo sobre el conjunto de prueba
- Exactitud
"""

#Evaluación sobre el conjunto de prueba
from sklearn import metrics

print(f'Exactitud: {model.evaluate(X_test,Y_test)}') #Exclusiva de Redes neuronales

"""# 5. Predicción para datos futuros

- Cargamos los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos los datos futuros
data_fut = pd.read_excel("alfabeto.xlsx", sheet_name = 1)
data_fut.head()

#Hacemos la predicción
Y_fut = model.predict(data_fut)
print(Y_fut.round())
fut = Y_fut.round()
enc.inverse_transform(fut.astype("int64"))