# -*- coding: utf-8 -*-
"""Practica Red Neuronal Back & Profunda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f0scLMvpnJgGXiytf3J75B1OiNOcjHik

# Practica Redes neuronales - Tema 1
# Juan Camilo Restrepo Velez - 000373886
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# 1. Preparación de Datos
-  Cargamos los datos
-  Conocemos los datos con estadísticos
- Transformación de datos  (sklearn sólo analiza variables numéricas)
"""

#Cargamos los datos
data = pd.read_excel("ObservatorioLaboral - tema1.xlsx", sheet_name=0) 
data.head()

#Conocemos los datos
data.info() #Informacion sobre cada columna, tipo y numero de registros

#Corrección del tipo de datos
data['Area_del_Conocimiento']=data['Area_del_Conocimiento'].astype('category')
data['Sexo']=data['Sexo'].astype('category')
data['Trabaja']=data['Trabaja'].astype('category')
data.info()

#Descripción de variables numéricas
print(data.describe());
data.plot.hist(bins=5);

#Descripción variables categóricas
data['Area_del_Conocimiento'].value_counts().plot(kind='bar')

#Descripción variables categóricas
data['Sexo'].value_counts().plot(kind='bar')

#Descripción variables categóricas
data['Trabaja'].value_counts().plot(kind='bar')

#Sklearn sólo analiza variables numéricas entonces se pasan las variables tipo category a numeros
dummiesOutlook = pd.get_dummies(data['Area_del_Conocimiento']) 
data = data.drop('Area_del_Conocimiento', axis=1)
data = data.join(dummiesOutlook)
data.head()

#Se codifican las categorias de la variable objetivo
data["Sexo"]=data["Sexo"].replace({"Mujeres": 0, "Hombres": 1})
data["Trabaja"]=data["Trabaja"].replace({"No": 0, "Si": 1})
data.head()

"""# 2. División 70-30"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data.drop("Trabaja", axis = 1)
Y = data['Trabaja']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y)
Y_train.value_counts()

"""# 3. Aprendizaje del Modelo: A)Backpropagation"""

#Creación del modelo con el conjunto de entrenamiento
from sklearn.neural_network import MLPClassifier
modelMLP = MLPClassifier(activation = "identity", hidden_layer_sizes = (6), 
                     learning_rate = "adaptive", learning_rate_init = 0.01,
                     momentum = 0.09, max_iter = 100, verbose = True, random_state = 1)
modelMLP.fit(X_train, Y_train)

"""# B) Deep Learning"""

#Creación del modelo con el conjunto de entrenamiento
from keras.models import Sequential
from keras.layers.core import Dense
#Red neuronal
modelDL = Sequential()
modelDL.add(Dense(3, input_dim = 10, activation = 'sigmoid'))
modelDL.add(Dense(2, activation = 'sigmoid'))
modelDL.add(Dense(1, activation = 'relu')) # Capa de salida
modelDL.compile(loss = 'mean_squared_error', optimizer = 'adam', metrics = ['accuracy'])
modelDL.fit(X_train, Y_train, epochs=100)

"""# 4. Evaluación del modelo sobre el conjunto de prueba
- Exactitud
"""

#Evaluación sobre el conjunto de prueba
from sklearn import metrics

Y_pred = modelMLP.predict(X_test) 

acc=metrics.accuracy_score(Y_test, Y_pred)
print(f'Exactitud: {acc}')

#Evaluación sobre el conjunto de prueba
from sklearn import metrics

print(f'Exactitud: {modelDL.evaluate(X_test,Y_test)}') #Exclusiva de Redes neuronales

"""# 5. Predicción para datos futuros

- Cargamos los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos los datos futuros
data_fut = pd.read_excel("ObservatorioLaboral - tema1.xlsx", sheet_name=1) 
data_fut.head()

dummiesOutlookFut = pd.get_dummies(data_fut['Area_del_Conocimiento']) 
data_fut = data_fut.drop('Area_del_Conocimiento', axis=1)
data_fut = data_fut.join(dummiesOutlookFut)
data_fut["Sexo"]=data_fut["Sexo"].replace({"Mujeres": 0, "Hombres": 1})
data_fut.head()

#Hacemos la predicción
Y_fut = modelMLP.predict(data_fut)
print(Y_fut)

#Hacemos la predicción
Y_fut = modelDL.predict(data_fut)
print(Y_fut.round())