# -*- coding: utf-8 -*-
"""Calidad Aire - S.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOnzcesRANxdOhbQDYil49gb4HFOxB31
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# 1. Preparación de Datos
-  Cargamos los datos
-  Conocemos los datos con estadísticos
- Transformación de datos  (sklearn sólo analiza variables numéricas)
"""

#Cargamos los datos
data = pd.read_excel("prediccionCalidadAire.xlsx", sheet_name=0) # sheet_name = 0 - primera hoja
data.head()

#Conocemos los datos
data.info() #Informacion sobre cada columna, tipo y numero de registros

#Corrección del tipo de datos
data['outlook']=data['outlook'].astype('category')
data['Alert']=data['Alert'].astype('category')
data.info()

#Descripción de variables numéricas
print(data.describe());
data.plot.hist(bins=5);

#Descripción variables categóricas
data['outlook'].value_counts().plot(kind='bar')

#Descripción variables categóricas
data['Alert'].value_counts().plot(kind='bar')

#Sklearn sólo analiza variables numéricas entonces se pasan las variables tipo category a numeros
dummiesOutlook = pd.get_dummies(data['outlook']) 
data = data.drop('outlook', axis=1)
data = data.join(dummiesOutlook)
data.head()

#Se codifican las categorias de la variable objetivo
data["Alert"]=data["Alert"].replace({"Yes": 1, "No": 0}) 
data.head()

"""# 2. División 70-30"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data.drop("Alert", axis = 1)
Y = data['Alert']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y)
Y_train.value_counts()

"""# 3. Aprendizaje del Modelo: A)Arbol de decisión"""

#Creación del modelo con el conjunto de entrenamiento
from sklearn import tree 
model = tree.DecisionTreeClassifier(min_samples_leaf=2, max_depth=10)
model.fit(X_train, Y_train)

from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
var_predictoras = X.columns.values
nom_clases= ['No','Yes']
export_graphviz(model, feature_names=var_predictoras, class_names= nom_clases, out_file=dot_data,filled=True, rounded=True,special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

"""# B) KNN"""

#Creación del modelo con el conjunto de entrenamiento
from sklearn import neighbors 
model = neighbors.KNeighborsClassifier(n_neighbors=3, metric='euclidean') #(n_neighbors=#DeVecinos, metric='TipoDeDistancia')
model.fit(X_train, Y_train)

"""# 4. Evaluación del modelo sobre el conjunto de prueba
- Exactitud
"""

#Evaluación sobre el conjunto de prueba
from sklearn import metrics

Y_pred = model.predict(X_test) 

acc=metrics.accuracy_score(Y_test, Y_pred)
print(f'Exactitud: {acc}')

"""# 5. Predicción para datos futuros

- Cargamos los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos los datos futuros
data_fut = pd.read_excel("prediccionCalidadAire-futuro.xlsx", sheet_name=0)
data_fut.head()

dummiesOutlookFut = pd.get_dummies(data_fut['outlook']) 
data_fut = data_fut.drop('outlook', axis=1)
data_fut = data_fut.join(dummiesOutlookFut)
data_fut.head()

#Hacemos la predicción
Y_fut = model.predict(data_fut)
print(Y_fut)