# -*- coding: utf-8 -*-
"""Procesamiento de imagenes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JcCJK5_vNJpVu8brxQ0kAyfs1llGAhU6

#Vision Artificial - Procesamiento de imagen
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Instalación de paquetes para tratamiento de imagenes
from PIL import Image

#Cargamos la imagen
img = Image.open("imagen1.jpg")
img

#Información sobre la imagen
print(img.size)
print(img.mode)
print(img.format)

#Rotamos la imagen
img.rotate(45)

#Extraer parte de la imagen
mat = np.asarray(img) #Convertir a matriz
img_new = mat[100:200, 180:260] #Recortar imagen
Image.fromarray(img_new.astype(np.uint8)) #Volver a imagen

#Convertir a escala de grises
img_Gris = img.convert('L')
img_Gris

#Guardamos la nueva imagen
img_Gris.save("img_gris.jpg")

#Representacion en vector de caracteristicas: Histograma
hist = img.histogram()
print(np.size(hist))
print(hist)

for i in range(0, 768):
  if i < 256: 
    c = 'red'
  else:
    if i < 512:
      c = 'green'
    else:
      c = 'blue'
  plt.bar(i, height = hist[i], color = c, edgecolor = c)

"""#Imagen # 2"""

#Cargamos la imagen
img2 = Image.open("imagen2.jpg")
img2

#Información sobre la imagen
print(img2.size)
print(img2.mode)
print(img2.format)

#Extraer parte de la imagen
mat = np.asarray(img2) #Convertir a matriz
img2_new = mat[200:300, 350:480] #Recortar imagen (Alto - Ancho)
Image.fromarray(img2_new.astype(np.uint8)) #Volver a imagen

#Representacion en vector de caracteristicas: Histograma
hist2 = img2.histogram()
print(np.size(hist2))
print(hist2)

for i in range(0, 768):
  if i < 256: 
    c = 'red'
  else:
    if i < 512:
      c = 'green'
    else:
      c = 'blue'
  plt.bar(i, height = hist2[i], color = c, edgecolor = c)

"""#Imagen # 3"""

#Cargamos la imagen
img3 = Image.open("imagen3.jpg")
img3

#Información sobre la imagen
print(img3.size)
print(img3.mode)
print(img3.format)

#Representacion en vector de caracteristicas: Histograma
hist3 = img3.histogram()
print(np.size(hist3))
print(hist3)

for i in range(0, 768):
  if i < 256: 
    c = 'red'
  else:
    if i < 512:
      c = 'green'
    else:
      c = 'blue'
  plt.bar(i, height = hist3[i], color = c, edgecolor = c)